### ISSUE TITLE
'homebridge-dht22@*' is not in the npm registry.

### ISSUE THREAD

**Issue by edugrt** [aaronhktan/homebridge-dht22#3]
Hello, @aaronhktan 

This plugin is precisely what I was looking for but it seems there is nothing on the NPM registry. How do I install it?

Thanks!

**Comment by aaronhktan** [comment]
Hey, @edugrt! You should be able to clone this repository, `cd` into the folder where you cloned it, and then run `npm i`.

e.g.
```
git clone https://github.com/aaronhktan/homebridge-dht22.git
cd homebridge-dht22
npm i
```

Good luck!
